services:
  postgres:
    image: postgres:16-alpine
    container_name: medipass-postgres
    environment:
      POSTGRES_DB: medipass
      POSTGRES_USER: medipass
      POSTGRES_PASSWORD: medipass
    ports:
      - "5432:5432"
    volumes:
      - medipass-pgdata:/var/lib/postgresql/data
      - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medipass -d medipass"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: medipass-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: medipass-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: medipass-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  medipass-pgdata:
