/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsurersRouteImport } from './routes/insurers'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsurersRoute = InsurersRouteImport.update({
  id: '/insurers',
  path: '/insurers',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/insurers': typeof InsurersRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/insurers': typeof InsurersRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/insurers': typeof InsurersRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/compliance'
    | '/disputes'
    | '/help'
    | '/hospitals'
    | '/insurers'
    | '/login'
    | '/patients'
    | '/pharmacies'
    | '/settings'
    | '/system'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/compliance'
    | '/disputes'
    | '/help'
    | '/hospitals'
    | '/insurers'
    | '/login'
    | '/patients'
    | '/pharmacies'
    | '/settings'
    | '/system'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/compliance'
    | '/disputes'
    | '/help'
    | '/hospitals'
    | '/insurers'
    | '/login'
    | '/patients'
    | '/pharmacies'
    | '/settings'
    | '/system'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  ComplianceRoute: typeof ComplianceRoute
  DisputesRoute: typeof DisputesRoute
  HelpRoute: typeof HelpRoute
  HospitalsRoute: typeof HospitalsRoute
  InsurersRoute: typeof InsurersRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  PharmaciesRoute: typeof PharmaciesRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurers': {
      id: '/insurers'
      path: '/insurers'
      fullPath: '/insurers'
      preLoaderRoute: typeof InsurersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  ComplianceRoute: ComplianceRoute,
  DisputesRoute: DisputesRoute,
  HelpRoute: HelpRoute,
  HospitalsRoute: HospitalsRoute,
  InsurersRoute: InsurersRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  PharmaciesRoute: PharmaciesRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
