/** @type {import('tailwindcss').Config} */
module.exports = {
    // NOTE: Update this to include the paths to all of your component files.
    content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            colors: {
                primary: "var(--color-primary)",
                "primary-light": "var(--color-primary-light)",
                "primary-fg": "var(--color-primary-fg)",
                secondary: "var(--color-secondary)",
                "secondary-fg": "var(--color-secondary-fg)",
                success: "var(--color-success)",
                "success-fg": "var(--color-success-fg)",
                error: "var(--color-error)",
                "error-fg": "var(--color-error-fg)",
                info: "var(--color-info)",
                "info-fg": "var(--color-info-fg)",
                background: "var(--color-background)",
                "background-grey": "var(--color-background-grey)",
                foreground: "var(--color-foreground)",
                "text-primary": "var(--color-text-primary)",
                "text-secondary": "var(--color-text-secondary)",
                border: "var(--color-border)",
                input: "var(--color-input)",
                ring: "var(--color-ring)",
                overlay: "var(--color-overlay)",
                "allergy-bg": "var(--color-allergy-bg)",
                "allergy-text": "var(--color-allergy-text)",
                card: "var(--color-card)",
                muted: "var(--color-muted)",
                "muted-fg": "var(--color-muted-fg)",
                accent: "var(--color-accent)",
                "accent-fg": "var(--color-accent-fg)",
            },
            spacing: {
                xs: "8px",
                sm: "12px",
                md: "20px",
                lg: "28px",
                xl: "36px",
                xxl: "48px",
                xxxl: "64px",
            },
            borderRadius: {
                sm: "10px",
                md: "14px",
                lg: "18px",
                xl: "24px",
                pill: "999px",
            },
        },
    },
    plugins: [],
};
